### ISSUE TITLE
Error deploying Sonarqube with internal postgres database

### ISSUE THREAD

**Issue by tylerauerbeck** [banzaicloud/banzai-charts#1003]
**Describe the bug**
When deploying Sonarqube, the sonarqube pod enters the `CreateContainerConfigError` state as it expects to find the key `postgres-password` in the sonarqube postgresql secret that is created. When evaluating the sonarqube postgresql secret, it appears that the key that is being created is `postgresql-password`. This needs to be fixed in order to allow the install to move forward.

**Steps to reproduce the issue:**
- `helm install banzaicloud-stable/sonarqube --version 0.7.3 -n my-namespace --generate-name`
- Watch the pod enter the `CreateContainerConfigError` state
- View the contents of the sonarqube postgresql secret and see that the key is set to `postgresql-password`

**Expected behavior**
When running a default install, I expect Sonarqube to be deployed with an internal postgres database so that I am then able to access the application.

**Screenshots**
N/A

**Additional context**
Running a default install per instructions on https://hub.helm.sh/charts/banzaicloud-stable/sonarqube

**Comment by pbalogh-sa** [comment]
@tylerauerbeck  Thanks for reporting this. We will dig into it and fix it as soon as possible.

**Comment by pbalogh-sa** [comment]
@tylerauerbeck  The fix has just released: https://github.com/banzaicloud/banzai-charts/releases/tag/sonarqube%2F0.8.0
