### ISSUE TITLE
[Thanos Chart] Ruler mistakenly tries to use gRPC by default

### ISSUE THREAD

**Issue by AlexDHoffer** [banzaicloud/banzai-charts#1030]
**Describe the bug**
When you apply the Thanos chart with Ruler enabled, the --query flag sets it automatically to try and use gRPC. Problem is, rules are sent to the Querier instance(s) for evaluation ONLY by HTTP. Your Ruler instance's logs will complain that Querier sent back an invalid HTTP response, since it's hitting the gRPC endpoint with HTTP content.

The bug in question can be found here: https://github.com/banzaicloud/banzai-charts/blob/master/thanos/templates/rule-statefulset.yaml#L73

This line needs to be changed to utilize the HTTP endpoint of the Querier instance(s) instead.

For evidence that Ruler can only query Querier using its HTTP endpoint, see this GitHub issue: https://github.com/thanos-io/thanos/issues/2020#issuecomment-580915171

**Steps to reproduce the issue:**
Enable queryDNSDiscovery in your values file. Enable Ruler. Attempt to apply the Helm chart with a valid rule. Then, take a look at the logs for Ruler to see it repeatedly trying and failing to POST the message to the gRPC endpoint.

**Expected behavior**
Ruler should be able to successfully send a rule to a Querier instance, have it evaluate the rule, and send the result back to Ruler.

**Comment by LilaNKM** [comment]
The change on the fix seem incomplete.

` - "--query=dnssrv+_grpc._tcp.{{ include "thanos.componentname" (list $ "query") }}-http.{{ .Release.Namespace }}.svc.cluster.local"
`
rather be 

`- "--query=dnssrv+_http._tcp.{{ include "thanos.componentname" (list $ "query") }}-http.{{ .Release.Namespace }}.svc.cluster.local"`
