### ISSUE TITLE
[Thanos Chart] PVC per Thanos Store replica

### ISSUE THREAD

**Issue by jshrack-ssi** [banzaicloud/banzai-charts#1067]
**Is your feature request related to a problem? Please describe.**

Kinda.

**Describe the solution you'd like to see**

While the chart supports PVC creation for a store containers, it does not appear to support a PVC per Thanos Store replica when deploying multiple replicas and/or multiple time partitions. I'd like to have a PVC per Thanos Store container given using emptydir is very intensive on K8s node root disk IO.

**Describe alternatives you've considered**

Emptydir

**Additional context**

Using three replicas per store time partition for HA. Perhaps I am doing deploying inproperly?

**Comment by kuberkaul** [comment]
have the same issue, while you can create three stores, the PVC created is only one, need that tunable to multiple PVC.

**Comment by tarokkk** [comment]
By default, store uses empty dir if no backend specified. Creating PVC/time replica seems reasonable.
