### ISSUE TITLE
Missing external metric resources

### ISSUE THREAD

**Issue by lonnix** [banzaicloud/banzai-charts#1089]
**Describe the bug**
Helm chart installation does not register custom or external resources

**Steps to reproduce the issue:**
```
helm install kube-metrics-adapter banzaicloud-stable/kube-metrics-adapter --version 0.1.3
```

**Expected behavior**
I expected some metrics to be registered.

**Screenshots**
Output of registered resources
```
~: kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[]}
~: kubectl get --raw /apis/external.metrics.k8s.io/v1beta1
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"external.metrics.k8s.io/v1beta1","resources":[]}
```

**Additional context**
I am new to this adapter, so it is possible I am just missing something. I had previously installed the zalando kube-metrics-adapter that this was based on and I know that there were registered resources for custom metrics from that one, but it also did not have registered external resources. I am trying to use an external metric to make http requests to an API outside of my cluster. 

Kubernetes version: 1.14
EKS version: 8
Helm version: v3.0.2

**Comment by sancyx** [comment]
`kube-metrics-adapter` doesn't expose any external or custom metrics by default on these API endpoints, you can setup different collectors like Prometheus collector. To have a Promethues query exposed as an external metrics you need to setup an HPA resource with correct annotations as described here: https://github.com/banzaicloud/kube-metrics-adapter#example-external-metric. You can use it with https://github.com/banzaicloud/hpa-operator which creates an annotated HPA for your deployment. You can install both using hpa-operator chart:  https://github.com/banzaicloud/hpa-operator/tree/master/deploy/charts/hpa-operator.
