### ISSUE TITLE
Allow to set `--set Thanos.createCustomResource=false` CustomResources required via helm chart

### ISSUE THREAD

**Issue by tarunptala** [banzaicloud/banzai-charts#1093]
**Thanos helm chart bug**
Allow to set `false` to install custom-resources if they are already installed in the cluster. something like prometheus-operator charts does with `--set prometheusOperator.createCustomResource=false`
```
alertmanagers.monitoring.coreos.com       
podmonitors.monitoring.coreos.com            
prometheuses.monitoring.coreos.com           
prometheusrules.monitoring.coreos.com       
servicemonitors.monitoring.coreos.com       
thanosrulers.monitoring.coreos.com            
```

**Steps to reproduce the issue:**
We had these CRDs already installed in the clusters. 

### Error 
```
MacBook-Pro-7$ helm upgrade --install thanos . --namespace monitoring -f thanos-values.yaml 
Release "thanos" does not exist. Installing it now.
Error: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists
```

**Expected behavior**
To allow something like `--set Thanos.createCustomResource=false`

**Comment by tarokkk** [comment]
This is some misunderstanding as we don't install any Prometheus related resources via our Thanos Helm chart.

**Comment by tarunptala** [comment]
@tarokkk thanks, wondering why do i get following error with `thanos` helm chart.
```
Error: customresourcedefinitions.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" already exists
```
