### ISSUE TITLE
Thanos chart support for newer version of Thanos

### ISSUE THREAD

**Issue by alexanderccc** [banzaicloud/banzai-charts#1104]
**Is your feature request related to a problem? Please describe.**
Not really, if trying to use thanos v13 image, thanos bucket would not start because of a missing argument

**Describe the solution you'd like to see**
adding - "tools" as the first argument in the deployment of thanos bucket

**Describe alternatives you've considered**
none

**Additional context**

The helm chart seems to work fine with the latest version of thanos, the only issue is with thanos bucket deployment which is missing an argument. It seems that giving it as an extra argument inside the helm chart is not working. This should be an easy change, just adding tools to the arguments hardcoded in the deployment of thanos.

**Comment by wiardvanrij** [comment]
Relates to this PR: https://github.com/thanos-io/thanos/pull/2513

> Tools: Moved thanos bucket commands to thanos tools bucket, also
moved thanos check rules to thanos tools rules-check. thanos tools rules-check also takes rules by --rules repeated flag not argument anymore.

**Comment by alexanderccc** [comment]
Created PR #1105 that should fix this
