### ISSUE TITLE
Query frontend support for Thanos chart

### ISSUE THREAD

**Issue by shaikatz** [banzaicloud/banzai-charts#1139]
Hi, I would like to see addition of Thanos [query frontend](https://thanos.io/components/query-frontend.md/) to the chart.

**Comment by galexrt** [comment]
@shaikatz You can already configure the query frontend in the Thanos chart, see https://github.com/banzaicloud/banzai-charts/blob/master/thanos/values.yaml#L183-L380

**Comment by shaikatz** [comment]
The query frontend is a new component that proxy requests to the proxy you've mentioned.
But I've just found it it hasn't released as stable yet (only in rc) version so it probably too early to add it to the chart. maybe next week :-) 

I'll close it for now.

**Comment by shaikatz** [comment]
Reopening since Thanos 0.15.0 was released and query frontend support is now required :-)

**Comment by wizard580** [comment]
I tested this with manually created deployment, service and ingress and it works SUPER. Just a bit of tweaking from default params. 
I really want this support in this chart. 

If no one wants to do - I can do MR myself :)

**Comment by shaikatz** [comment]
@wizard580 go for it! looking forward.

**Comment by bueti** [comment]
I couldn't wait any longer, thus I gave it a try :) please check PR #1195
