### ISSUE TITLE
[Grafana] Reference to invalid Prometheus Operator template

### ISSUE THREAD

**Issue by ncrothe** [banzaicloud/banzai-charts#1144]
**Describe the bug**
I tried to deploy the Grafana Operator helm chart in "scan all namespaces" mode and it failed because the clusterrole template references a template "prometheus-operator.fullname".

**Steps to reproduce the issue:**
Deploy grafana operator helm chart with args.scanAllNamespaces: true
See Error: template: grafana-operator/templates/clusterrole.yaml:6:20: executing "grafana-operator/templates/clusterrole.yaml" at <{{template "prometheus-operator.fullname" .}}>: template "prometheus-operator.fullname" not defined

**Expected behavior**
Chart deploys without error.

**Screenshots**

**Additional context**
Looks like a copy&paste from the prom operator in https://github.com/banzaicloud/banzai-charts/blob/master/grafana-operator/templates/clusterrole.yaml#L6 as well as https://github.com/banzaicloud/banzai-charts/blob/master/grafana-operator/templates/clusterrole.yaml#L8.

**Comment by ahma** [comment]
@ncrothe Thanks for the report!
