### ISSUE TITLE
[grafana-operator] Use latest release of integr8ly/grafana-operator 3.6.0 & support customFolderName

### ISSUE THREAD

**Issue by rbs4ba** [banzaicloud/banzai-charts#1178]
**Is your feature request related to a problem? Please describe.**
I'd love to see support for the latest integr8ly/grafana-operator release 3.6.0, particularly the functionality for `customFolderName` for dashboards. I see that not too long ago you all swapped away from integr8ly, I guess [due to some bug](https://github.com/banzaicloud/banzai-charts/commit/f499a882608bf088eda94befa6ea3385cabd201a). Is there any plan for moving back to integr8ly's operator and adding support for the `customFolderName` field for the `GrafanaDashboard` CRD?

**Describe the solution you'd like to see**
Make use of integr8ly/grafana-operator's latest release and add support for the `customFolderName` functionality

**Comment by ahma** [comment]
Hi @razaj92, This is good news!  We'll check it and if it works well we'll drop our version. Thanks!
