### ISSUE TITLE
Thanos: Query igress render issue

### ISSUE THREAD

**Issue by buker** [banzaicloud/banzai-charts#1181]
**Describe the bug**
This is how current template is rederd:
# Source: thanos/templates/query-ingress.yml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thanos-query-http
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-0.3.28
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.15.0
    app.kubernetes.io/component: query
      realm: internal
spec:
  tls:
    - hosts:
        - "query-thanos.dev-internal.example.com"
      secretName: dev-internal.example.com
  rules:
    - host: query-thanos.dev-internal.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: thanos-query-http
              servicePort: 10902

For values:
query:
  http:
    ingress:
      enabled: true
      labels: 
        realm: internal
      hosts: [query-thanos.dev-internal.example.com]
      path: "/"
      tls:
      - hosts:
        - query-thanos.dev-internal.example.com
        secretName: dev-internal.example.com

Correct should be:
# Source: thanos/templates/query-ingress.yml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thanos-query-http
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-0.3.28
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.15.0
    app.kubernetes.io/component: query
    realm: internal
spec:
  tls:
    - hosts:
        - "query-thanos.dev-internal.example.com"
      secretName: dev-internal.example.com
  rules:
  - host: query-thanos.dev-internal.example.com
    http:
      paths:
        - path: /
           backend:
            serviceName: thanos-query-http
            servicePort: 10902
**Steps to reproduce the issue:**
helm template

**Comment by giovannirco** [comment]
Having issues as well, did someone take a look at the PR?
