### ISSUE TITLE
Thanos chart v0.3.30 no longer exists in repo

### ISSUE THREAD

**Issue by mikesplain** [banzaicloud/banzai-charts#1201]
**Describe the bug**

Hello there! We upgraded to your great Thanos chart a few weeks ago `v0.3.30` and since this weekend we have been unable to pull down this version.  
**Steps to reproduce the issue:**

```
$ helm show chart banzaicloud-stable/thanos
apiVersion: v1
appVersion: 0.15.0
description: Thanos is a set of components that can be composed into a highly available
  metric system with unlimited storage capacity, which can be added seamlessly on
  top of existing Prometheus deployments.
icon: https://raw.githubusercontent.com/thanos-io/thanos/master/docs/img/Thanos-logo_fullmedium.png
keywords:
- thanos
- prometheus
- metrics
maintainers:
- email: info@banzaicloud.com
  name: Banzai Cloud
name: thanos
sources:
- https://github.com/thanos-io/thanos
- https://github.com/banzaicloud/banzai-charts/tree/master/thanos
version: 0.3.29
```
**Expected behavior**

0.3.30 should still be there accessible.

**Additional context**

I assume some automation may have gone wrong with #1191 or #1192 that may have removed the chart?

Thanks!

**Comment by ahma** [comment]
Hi, @mikesplain thanks for the issue I retagged this, now looks fine. 
`banzaicloud-stable/thanos         	0.3.30       	0.15.1     	Thanos is a set of components that can be compo...`
