### ISSUE TITLE
How to install one zookeeper operator per namespace?

### ISSUE THREAD

**Issue by krishnachalla-hv** [banzaicloud/banzai-charts#1211]
In my current project we creating multi tenant application. For that I need to install zookeeper operator and solr operator per namespace. In the solr operator there is flag `watchnamespaces: true` then it will watch only that particular namespace. In zookeeper operator there is a same kind of flag but not working for me. 
lets say I installed zookeeper operator for tenant-1 like below
`helm install t0 banzaicloud-stable/zookeeper-operator -n tenant-1 --set watchnamespace=tenant-1`
then again I tried to install in tenant-2 namespace
`helm install t0 banzaicloud-stable/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2`
getting the below error
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "zookeeperclusters.zookeeper.pravega.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "tenant-2": current value is "tenant-1"`
Any help would be much appreciated. Thanks in  advance.

**Comment by stoader** [comment]
This helm chart was created for our needs. I suggest using the official zookeeper operator helm chart from here: https://github.com/pravega/zookeeper-operator/tree/master/charts/zookeeper-operator
