### ISSUE TITLE
[Cadence] Chart doesn't allow passing annotations or labels to services

### ISSUE THREAD

**Issue by johnkost** [banzaicloud/banzai-charts#1303]
**Describe the bug**
When configuring the Cadence chart on EKS using the AWS Load Balancer Controller, we need to be able to set annotations on the services. The chart doesn't currently allow setting additional annotations. 

**Steps to reproduce the issue:**
N/A

**Expected behavior**
The chart allows deploying additional annotations on services. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by pregnor** [comment]
Released in tag [cadence/0.21.3](https://github.com/banzaicloud/banzai-charts/releases/tag/cadence%2F0.21.3), chart version 0.21.3.
