### ISSUE TITLE
Helm Chart Certificate Expired

### ISSUE THREAD

**Issue by pseymournutanix** [banzaicloud/banzai-charts#1331]
Hello, you probably know this but your certificate has expired on you helm chart repo:-

```
* Connected to kubernetes-charts.banzaicloud.com (35.184.233.214) port 443 (#0)
...
* Server certificate:
*  subject: CN=*.banzaicloud.com
*  start date: Sep 20 07:42:56 2022 GMT
*  expire date: Dec 19 07:42:55 2022 GMT
```

Thanks.

**Comment by fplantinga-guida** [comment]
We are seeing this issue as well. 

`failed to fetch Helm repository index: failed to cache index to temporary file: Get "https://kubernetes-charts.banzaicloud.com/index.yaml": x509: certificate has expired or is not yet valid: current time 2022-12-19T08:34:16Z is after 2022-12-19T07:42:55Z`

**Comment by mzeeshan1** [comment]
+1

**Comment by bergethon** [comment]
+1

**Comment by pregnor** [comment]
Thanks for the report, the certificates have been renewed, apologies for the inconvenience.
