### ISSUE TITLE
helm repository DNS record gone

### ISSUE THREAD

**Issue by DesmondH0** [banzaicloud/banzai-charts#1349]
**Describe the bug**
Looks like banzaicloud helm repo domain DNS record is not resolvable from public DNS
Domain: kubernetes-charts.banzaicloud.com

**Steps to reproduce the issue:**
```bash
#> dig kubernetes-charts.banzaicloud.com @8.8.8.8 +short
(empty result)
#> dig kubernetes-charts.banzaicloud.com @1.1.1.1 +short
(empty result)

#> helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
Error: looks like "https://kubernetes-charts.banzaicloud.com" is not a valid chart repository or cannot be reached: Get "https://kubernetes-charts.banzaicloud.com/index.yaml": dial tcp: lookup kubernetes-charts.banzaicloud.com on ${my_DNS}:53: server misbehaving
```

**Expected behavior**
Able to resolve and add the repo as expected

**Comment by bbl232** [comment]
Ditto

**Comment by ChrisMcKenzie** [comment]
Is there any update on this? 

thanks

**Comment by nerzhul** [comment]
same issue here, and we forgot to cache it ahem

**Comment by nerzhul** [comment]
their DNS zone is totally broken

```
❯ drill SOA banzaicloud.com
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 51178
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; banzaicloud.com.	IN	SOA
```

**Comment by francoisferrand** [comment]
Looking at DNS history, it seems this used to alias to banzaicloud-kubernetes-charts.prod.eticloud.io, which is still up: so the charts may still be available there, if that helps

**Comment by AdamWyzgol** [comment]
Is Banzai Cloud closed by Cisco? looks like most valuable part that was Bank Vaults was moved to new organization so is that means Banzai Cloud is dead?

**Comment by morphalus** [comment]
I think that is a classic issue. Forgot to pay the bill or something like that.

**Comment by lgecse** [comment]
@DesmondH0 thanks for reporting the issue. There is a temporary disruption in the legacy Banzai Cloud AWS account, affecting the helm repository. Our SRE team is actively working to resolve this issue. We apologize for any inconvenience and appreciate your patience. We'll keep you updated on the progress.

**Comment by lgecse** [comment]
@DesmondH0 the repo should be accessible again, please let me know if we can close this issue.

**Comment by PsychoSid** [comment]
Working for me now. Thank you.

**Comment by DesmondH0** [comment]
Working for me as well, thanks a lot 💯

**Comment by bs-amitmahajan29** [comment]
This has occurred again (https://github.com/banzaicloud/banzai-charts/issues/1350), @lgecse can you please have a look at it?
