### ISSUE TITLE
Grafana not able to start on pipeline-cp due to PVC config problems

### ISSUE THREAD

**Issue by sancyx** [banzaicloud/banzai-charts#167]
Grafana logs:

chown: changing ownership of '/var/lib/grafana/dashboards/..data': Read-only file system
chown: changing ownership of '/var/lib/grafana/dashboards/..2018_03_19_17_25_51.132647244': Read-only file system
chown: changing ownership of '/var/lib/grafana/dashboards': Read-only file system

**Comment by kozmagabor** [comment]
We don't have pipeline-cp chart anymore.
