### ISSUE TITLE
Failed to install tidb

### ISSUE THREAD

**Issue by clanstyles** [banzaicloud/banzai-charts#206]
```
Error: file "banzaicloud-incubator/tidb" not found
```

Curl the end point ```http://kubernetes-charts-incubator.banzaicloud.com/``` You'll notice that urls is missing an h in the protocol (http://). I think that's what's causing it?

```
    urls:
    - ttp://kubernetes-charts-incubator.banzaicloud.com/tidb-0.0.1.tgz
```

**Comment by clanstyles** [comment]
I've confirmed this is the issue. Check ```~/.helm/repository/cache/banzaicloud-incubator-index.yaml``` and you'll notice it's mssing the ```h````. After fixing that it all worked.

**Comment by matyix** [comment]
hello @clanstyles  - thank for reporting this. most of us are at KubeCon this week but once we are back home we'll fix this. @ahma

**Comment by kozmagabor** [comment]
Hello @clanstyles Thanks for your report.
Please use chart repo from the master branch.
Currently, the http://kubernetes-charts-incubator.banzaicloud.com/, which is created from the ` 0.3.0` release is include this bug. :(
The fix will be available in the next release. 

Until then use this chart repo from the **master** branch 
http://kubernetes-charts-incubator.banzaicloud.com/branch/master

**Comment by kozmagabor** [comment]
We fixed it.
