### ISSUE TITLE
[vault] drop default file storage

### ISSUE THREAD

**Issue by so0k** [banzaicloud/banzai-charts#214]
The vault chart default values set `vault.config.storage` to `file` - when adding `s3` configuration you end up configuring 2 storage backends.

Helm is supposed to drop a key if you set it to `null` https://github.com/kubernetes/helm/pull/2648 - but this didn't seem to work, is it an issue having 2 storage backends configured and is there a way to delete default keys?

**Comment by bonifaido** [comment]
Hi, I haven't managed to delete the value either but found that other people are also having an issue with the key deletion (https://github.com/kubernetes/helm/issues/3117), I will come back with a solution pretty soon, probably there will be no default storages defined in values for now, and if it is empty I will add the file storage.

**Comment by bonifaido** [comment]
The fix is on the way: https://github.com/banzaicloud/banzai-charts/pull/215
