### ISSUE TITLE
[spark] Using HDFS as storage

### ISSUE THREAD

**Issue by juvlarN** [banzaicloud/banzai-charts#222]
I wonder why the HDFS is not named as an option the https://github.com/banzaicloud/banzai-charts/tree/master/stable/spark-hs readme. 

I'd like to store history logs, app logs in HDFS as well as processing data that resides within the HDFS. Is this possible in the current stage of the project?

**Comment by matyix** [comment]
Hello @juvlarN 

At this time we don't support HDFS on Kubernetes, that's the reason why you can't configure it in the chart. We believe that there are better alternatives to HDFS - moreover, it brings an unnecessary level of complexity when using it with Kubernetes. Shortly, my personal opinion is that it does not fit, thus we don't plan to support it at this time.

**Comment by juvlarN** [comment]
@matyix  I see, thanks for the quick response.
Is it a lot of work to get this working though? I've looked through the spark charts and found several occurences where the storage system is mentioned. When I change all of those configuration settings, will I get it working to write to the HDFS? Or is there any limitation in the code itself?

**Comment by matyix** [comment]
It should not be and there are a few examples out there - to make it production ready it's a different question. You can check this session to consider some caveats: https://databricks.com/session/hdfs-on-kubernetes-lessons-learned
