### ISSUE TITLE
Updates needed to OpenFaaS chart

### ISSUE THREAD

**Issue by alexellis** [banzaicloud/banzai-charts#238]
Hi @bonifaido there are quite a few changes needed to bring your OpenFaaS chart into sync with master. Please see upstream for more details - https://github.com/openfaas/faas-netes/tree/master/chart/openfaas

Thanks,

Alex

**Comment by matyix** [comment]
Hello @alexellis - thanks for reporting, we are aware of. We are busy with a release but will definitely revise the chart and update after.

**Comment by alexellis** [comment]
Ping @matyix

**Comment by alexellis** [comment]
Thanks 👍
