### ISSUE TITLE
aws-kms-s3 configuration does not work in the vault chart.

### ISSUE THREAD

**Issue by BertieW** [banzaicloud/banzai-charts#275]
When setting values to use aws-kms-s3 backend for unsealing the vault in the values.yaml files, vault-unsealer fails with the following error message:

`level=fatal msg="error initializing vault: error testing keystore before init: MissingRegion: could not find region configuration"`

Using the following configuration for unseal:

> unsealer:
>   image:
>     repository: banzaicloud/bank-vaults
>     tag: master
>     pullPolicy: Always
>   args: [
>       "--mode",
>       "aws-kms-s3",
>       "--aws-kms-key-id",
>       "arn:aws:kms:region:account:key/xxxx-xxxxx-xxxxxx-xxxxxx",
>       "--aws-s3-bucket",
>       "bucket-name",
>       "--aws-s3-prefix",
>       "prefix"
>   ]

Have tried the following options as well without success:
1. using the full arn:s3 name for the bucket
2. Only the key id, no arn:aws:kms:etc
3. Enabling encryption with the right key on the bucket
4. Disabling encryption on the bucket.
5. Various tags both for bank-vaults and the vault image.

I've verified the IAM permissions on the instance running the deployment, and all are correct.

**Comment by BertieW** [comment]
After a few frustrating hours, found the following work-around:

in templates --> deployment, in the definition for vault-unsealer, inserted an AWS_REGION env variable with the value of the region where the s3 bucket resides. 

While works right now, a better solution would be to add a `--aws-s3-region` option to the arguments for `bank-vaults unseal --init` command since the region is clearly required for this to work correctly.

**Comment by bonifaido** [comment]
HI @BertieW ! Thank you for reporting this and sorry for the frustration that this issue caused. I'm opening up a new issue in Bank-Vaults, it definitely needs the region parameter.
