### ISSUE TITLE
unable to addd Helm repo. problem with helming

### ISSUE THREAD

**Issue by saikatharryc** [banzaicloud/banzai-charts#342]
while trying to do
[with `/` as well at the end]
```
helm repo add fb-1-stable https://s3-eu-west-1.amazonaws.com/kubernetes-charts.banzaicloud.com/branch/fb-1
```
getting error:
```
Error: Looks like "https://s3-eu-west-1.amazonaws.com/kubernetes-charts.banzaicloud.com/branch/fb-1/" is not a valid chart repository or cannot be reached: Failed to fetch https://s3-eu-west-1.amazonaws.com/kubernetes-charts.banzaicloud.com/branch/fb-1/index.yaml : 403 Forbidden
```

**Comment by kozmagabor** [comment]
Hi,

Thanks for your report.
You need to use a valid branch name, like `master`

Please use the following command to add the stable version from banzai chart repository.

`helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master`

Regards,
Gabor
