### ISSUE TITLE
Vault StatefulSet

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/banzai-charts#345]
Vault should be running in a StatefulSet such as in the banzaicloud/vault-operator: https://github.com/banzaicloud/bank-vaults/commit/b0b2315f2966622e3150fdae86c5b3762fda473b#diff-28590649c56bf5f88fc16d81abf6c197 to handle restart and HA matters.

**Comment by raoofm** [comment]
@bonifaido is this still on?

**Comment by bonifaido** [comment]
This is on hold right now, because as the way we handle Vault readinessProbes and some limitations in StatefulSet upgrade procedures are limiting this work. The operator can run Vault in a StatefulSet, because it can change the leader instance by calling a step-down call on it, so the StatefulSet can proceed to upgrade.

**Comment by bonifaido** [comment]
Fixed already.
