### ISSUE TITLE
Thanos chart is not yet available

### ISSUE THREAD

**Issue by harshal-shah** [banzaicloud/banzai-charts#379]
This article https://banzaicloud.com/blog/hands-on-thanos/ refers to a _soon to be released_ thanos chart but that chart is not yet available in banzai-stable repo. 

when is this chart going to be released?

**Comment by tarokkk** [comment]
Hi there!

We are working on some final improvements. The chart will be released next week. I will leave this issue open till then.

**Comment by tarokkk** [comment]
Close by #468
