### ISSUE TITLE
failed to download "banzaicloud-incubator/spot-termination-exporter"

### ISSUE THREAD

**Issue by estahn** [banzaicloud/banzai-charts#438]
```
helm install banzaicloud-incubator/spot-termination-exporter                  
Error: failed to download "banzaicloud-incubator/spot-termination-exporter" (hint: running `helm repo update` may help)
```

I followed the steps including `helm repo update` and got above error.

**Comment by bonifaido** [comment]
Hi @estahn, I guess you were following the README from the spot-termination-exporter itself, which contains the wrong link, in the repo's main README you can find the correct instructions, which are:
`helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master`
`helm repo update`
`helm install banzaicloud-stable/spot-termination-exporter`

I will fix the README in spot-termination-exporter. Thanks for reporting this.
