### ISSUE TITLE
[banzaicloud-stable/spot-termination-exporter] Should have nodeSelector or node(Anti)Affinity

### ISSUE THREAD

**Issue by estahn** [banzaicloud/banzai-charts#445]
Not all instances are spot instances and this daemon set should only go to instances flagged as spot instances.

**Comment by martonsereg** [comment]
Thanks for the feedback, I'll add the affinity and node selector fields to the values file so it will be configurable.

**Comment by estahn** [comment]
@martonsereg Awesome, thanks!
