### ISSUE TITLE
Add anchore config params to pipeline chart and tform

### ISSUE THREAD

**Issue by sancyx** [banzaicloud/banzai-charts#447]
Enable the following Anchore config params setup in pipeline chart: 
[anchore]
enabled = true
dialect = "postgres"
host = "localhost"
port = 5432
user = "anchore-db-user"
password = "xxxxxxxxxx"
dbname = "anchore"
endPoint = "https://beta.dev.banzaicloud.com"

**Comment by kozmagabor** [comment]
It doesn't need anymore.
