### ISSUE TITLE
Use helm version 2.10 new feature wait for crd in case of logging operator supporting charts

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/banzai-charts#455]
Sometimes helm install fails with crd not ready in these charts:
- s3-output chart
- gcs-output
- azure-output

**Comment by kozmagabor** [comment]
Please use --wait if you want to wait crd install.

**Comment by martonsereg** [comment]
wait is now implemented, see [#1377](https://github.com/banzaicloud/pipeline/pull/1377)
