### ISSUE TITLE
helm TiDB persistence failed

### ISSUE THREAD

**Issue by DavisLinDB** [banzaicloud/banzai-charts#46]
I try to use helm tidb.
Everything ok when using default setting:
`helm install --name my-release banzaicloud-incubator/tidb`

But failed when enable persistence.
The command is:
`helm install --name my-release --set tikv.persistence.enabled=true,tikv.persistence.accessMode=ReadWriteOnce,tikv.persistence.size=8Gi banzaicloud-incubator/tidb
`
Using GlusterFS + heketi for storage layer.

Information:

```
k get pv,pvc | grep tidb
pv/pvc-e431a826-001e-11e8-9529-021abc0baa27   9Gi        RWO            Delete           Bound     default/my-release-tidb         tidb  10m
pvc/my-release-tidb         Bound     pvc-e431a826-001e-11e8-9529-021abc0baa27   9Gi        RWO            tidb               10m

```

```
k get pods | grep tidb
my-release-tidb-db-5bfcb99b97-hvbln                              1/1       Running            0          14m
my-release-tidb-db-5bfcb99b97-jm2ds                              1/1       Running            0          14m
my-release-tidb-kv-68894f944-5fcfm                               1/1       Running            0          14m
my-release-tidb-kv-68894f944-jxm6b                               0/1       CrashLoopBackOff   7          14m
my-release-tidb-kv-68894f944-nhb8z                               0/1       CrashLoopBackOff   7          14m
my-release-tidb-pd-0                                             1/1       Running            0          14m
my-release-tidb-pd-1                                             1/1       Running            0          14m
my-release-tidb-pd-2                                             1/1       Running            0          14m                                           1/1       Running            0          11m

```
Only one kv-pod executed.  Two got errors.

k describe pod my-release-tidb-kv-68894f944-5fcfm
`Normal   SuccessfulMountVolume  19m                kubelet, ranchernode1  MountVolume.SetUp succeeded for volume "pvc-e431a826-001e-11e8-9529-021abc0baa27"
`
k describe pod my-release-tidb-kv-68894f944-jxm6b
`Normal   SuccessfulMountVolume  17m                kubelet, ranchernode1  MountVolume.SetUp succeeded for volume "pvc-e431a826-001e-11e8-9529-021abc0baa27"
`
k describe pod my-release-tidb-kv-68894f944-nhb8z
`Normal   SuccessfulMountVolume  19m                kubelet, ranchernode2  MountVolume.SetUp succeeded for volume "pvc-e431a826-001e-11e8-9529-021abc0baa27"
`
k logs my-release-tidb-kv-68894f944-5fcfm
No ERROR.

k logs my-release-tidb-kv-68894f944-jxm6b
`2018/01/23 09:43:57.020 tikv-server.rs:157: [ERROR] lock "/data/tikv" failed, maybe another instance is using this directory.
`

k logs my-release-tidb-kv-68894f944-nhb8z
`2018/01/23 09:43:45.272 tikv-server.rs:157: [ERROR] lock "/data/tikv" failed, maybe another instance is using this directory.`

The problem is that the second and the third pod mount the same storage?

**Comment by matyix** [comment]
Hello @DavisLinDB 

Please check this PR #56 - this should fix the problem. Thanks for reporting it.
