### ISSUE TITLE
[banzaicloud/productinfo] Wrong livenessProbe and readinessProbe path

### ISSUE THREAD

**Issue by estahn** [banzaicloud/banzai-charts#467]
Not changing `basePath` results in wrong `livenessProbe` and `readinessProbe` path.

```
            livenessProbe:
              httpGet:
-               path: /productinfo/status
+               path: //status
                port: http
            readinessProbe:
              httpGet:
-               path: /productinfo/status
+               path: //status
                port: http
```

**Comment by lpuskas** [comment]
Hi @estahn, thanks for reporting this; we'll look into it (or you could send a pull request with the fix - possibly that would be  faster)

**Comment by lpuskas** [comment]
@estahn,  we pushed the fix for this problem so closing the issue.
