### ISSUE TITLE
inconsistent fullname handling

### ISSUE THREAD

**Issue by orymate** [banzaicloud/banzai-charts#515]
full name of pipeline chart with release name like "pipeline-cp" is "pipeline-cp" instead of "pipeline-cp-pipeline" because the overlapping names. this causes for example drone to not reach the pipeline service by the composed name in its config

_Originally posted by @orymate in https://github.com/banzaicloud/banzai-charts/pull/514/comment#issuecomment-441575044_

**Comment by tarokkk** [comment]
The issue caused by the new templating introduces in Helm. It trims the `Chart name` from `Release Name` when it contains.
```
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
```
