### ISSUE TITLE
TLS issue with vault behind Ingress

### ISSUE THREAD

**Issue by aaktaev** [banzaicloud/banzai-charts#527]
After deploying vault HA , storage GCP getting error:
Error checking seal status: Get https://mydomain.com:8200/v1/sys/seal-status: x509: certificate signed by unknown authority
kubectl get secrets vault-vault-tls -o yaml
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lRRHVZdE9Pb2dmSVIxc1ZmQWhSbVYzekFOQmdrcWhraUc5dzBCQVFzRkFEQVQKTVJFd0R3WURWUVFERXdoMllYVnNkQzFqWVRBZUZ3MHhPREV4TWpreE1URXpNemRhRncweE9URXhNamt4TVRFegpNemRhTUJNeEVUQVBCZ05WQkFNVENIWmhkV3gwTFdOaE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQXp5TFpXYndkY2RDQUpJa0VGWVdOU2x6UVhkTWEva2FLcVo5eE5oT29FeFpOSkRXRlFsVVMKNGRvbks2eHIwdnh5Ni9pUFh3Q0dqU2plandlL2JOR2wra0FnOHlydTNaSW5qa1lGNUhCQXNtZjB4U3JyVHdhUwo5QVJybzZ4ZktmdnJxMWY1czJzM2oyT0lkUjNTdTM0cFdBM2pkOGxXRUxNRXFPdE0rTW1qNDBJN05EM3FUbXd1CndQeW43NjRYUDloZmw3UlZ1V2Z4QmZ2MVNiek41NEloNVVFdFp6TUM2Vjg4bUMxZ29nU0lUTEo1N3hxU01hN0QKdzZHTkd4cGlQWEMwSUE4b2FuR1JBUTMzeW9ESU1IWnZ4U2pMQVNVTTJ3UTFMaU9UYjhmTFVIRFpQT1VwbU1ZaQpmRjlYRytUOStabHFGOHJhaXlETWpRS2lVQ1dhcStHVkR3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DCkFxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUIKQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGZVFkVjYyS2JINVlqOERIWDNOUEp5QVk3S29HV3Y5bFVxcAo5R1BpeU85ajRNSmdwUGNsZDNZT013dWxyMlRWbkhmOWZhWDRzZm1ITktFeUVJOTVMdHZvZDdNeXdQakNScE54CmR2b0FwMXN3ODB5MVgwd2VpeDhyZytIWEhtdHczNnJMQWpqU0dYbGRRVUllQ2RaaFowTTM5eUNhbWxQc09rTDcKYURmNHpOYVpFeFhtN3Y2Y1ptc2FwRzNhS3lsekZKL2hxZ3lJb2o0d1lwU2tHcEZLRWRrK29Sdkx4WTJFQmdLWgpOdTN2TFhseWg0YnJScmk2aVo5YnA0SnpxUXl3N0RTK3lVZUtJWjhXaFpCTGdicmE2L0dIRWtXaDJ2VkRKZFBOCjJ1dGFKRHk0QUY5SUxBVlVQUTlabTliaUx0cG1EYWkvM21HU3d0MEloemM0S0xhcEtjMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  ca.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBenlMWldid2RjZENBSklrRUZZV05TbHpRWGRNYS9rYUtxWjl4TmhPb0V4Wk5KRFdGClFsVVM0ZG9uSzZ4cjB2eHk2L2lQWHdDR2pTamVqd2UvYk5HbCtrQWc4eXJ1M1pJbmprWUY1SEJBc21mMHhTcnIKVHdhUzlBUnJvNnhmS2Z2cnExZjVzMnMzajJPSWRSM1N1MzRwV0EzamQ4bFdFTE1FcU90TStNbWo0MEk3TkQzcQpUbXd1d1B5bjc2NFhQOWhmbDdSVnVXZnhCZnYxU2J6TjU0SWg1VUV0WnpNQzZWODhtQzFnb2dTSVRMSjU3eHFTCk1hN0R3NkdOR3hwaVBYQzBJQThvYW5HUkFRMzN5b0RJTUhadnhTakxBU1VNMndRMUxpT1RiOGZMVUhEWlBPVXAKbU1ZaWZGOVhHK1Q5K1pscUY4cmFpeURNalFLaVVDV2FxK0dWRHdJREFRQUJBb0lCQUVaUGlBUGp6UUxqU1h3ZApYbHVIMSt3VUVVNm42QlBFRWpGOXc4b2RaZ0lFb2U3V2xBTnVLVmlzMm5zQ3JoOFNQbGhIS1RPUVZCdjZjWUdQCm1iVHdmU3l6TS93VzZMb2hjSGZrNFA4bjgyNGJ4NFJlQ3ozcDkxd0pYQmhVM0lDOTJNTnl1M25odlJ4Wkp1cksKVXN2K0NUNndpRFFURGJuaGFvV0VTYjV4ZzhZU0NwdXBxM3hsaEZ1WmFYeHRnMytsQlR6SVVYM0RoQ29xZ3NBaApySE5ZTlkrTHZ6MlJmTUs4eEQxZmgxaEI3UzBBRENyem04a2h1ZGt6K1VNVFRqdWZYcDczUER3K2ZrRmtCaDlpCmZ1eUs4QzAybWtVcUpBQngyOERKUURmRUlVb29UQ3NmOXlJYVhtbVJEK2dmZy9oQTFZNW5ZUVRvUXkxZVRGVU0KZ1hZTzU5RUNnWUVBMXJtMk42TGc5MVdpbXNJT3d6SXZiSWI4bGFVdzdmdjJ2YktyU3hReDdVZCtoSFNTbmNlbgpZVE1xTk9JbmRBWGJGS1ZWbmtBa3FGQ2tVMnpoWjlQbnJ0ZmJaRytxOVZucklGRzdxNWo5Mm9HWDN6VTIxanBoClZuTThsT1FKK3ExclZnQnlPM2NSQ2pNeVIycm9ybytWbzFiK3ZYM3NoT1hHWGo3MnlKUHZ2SXNDZ1lFQTl2T3UKQjBBMktuNnY5Sk9kY1NHbmd5cTFEZXAvMnpub1dHY1RrMktCNHFOb09UZEx5V2c0UDUvNi9mOVRTdTExWitDZApXNlJycTJ3em9OaXQ3Vi8zSlhvSU9zcDdMazdrVm1pSmVhMUtpMFlGRUFhRjN3d1l1ci9vZXBCaTlnNTJTTUs5Cit2azB3VldpSllUdzJQVG5QVkJuQ1Y3QmhqYWFyYXRPcFNOVlJnMENnWUVBajZDblZ1MjNKeG43NnlLVTkxSVIKVUxtMktHN1huTWhtRWh0NTRuMStxK1dmcGYvSHRvdysxSkNCMGQvWVhnNHdyYzJ0eUczRlYyU2hsa0FGUWdzSApOUGVrQTdtQ0ZCMXlYaXJ0cW1scW5BY0ZURU52QzdyL012RmYrNFBSZlFFVkEvREdlQ283bHFRS0pLVkpRTUpBCmFJS2ZZS2JqVnozUEEybUFiMGd0R3VNQ2dZRUFyN3p0eFg4dWpNTW5HRmZNSE93a056VzNMcllJVXN3OHlseGcKRSt4d0hnYkhicUFwTUtVWUVqOFk4SlE0aEFQRUh5NDdEVEpPNU9qVlBNdTF5azBXcGZiWDBHNnpobHJpSjVPdwo4WVFlbmtvdjVCMmdPd0J5d01NOC82dXNvUW5kcHgzZThMRlRsNW9IRDhneFZWUERFMkVhVWhLNmlYWm1VTnl0CjFOcjJIaWtDZ1lBTFovN0tscWJTUnNYdWc3TUFKSjQzRXZpZ1phcHI3cFRpTXRubCtrWTFmVDd2dEx4eldSWU0KaHZWYmk4QnlCVmRvK0R4dlFtaEdJT3JpWlFKK1BCYVc4ejFXVnJkeFVEU0EweGRSUU1hNkxuMDFWSDlFUGFFZwprLzk4eVovTS9KS2FsWVpPMlRGYkVmWTJPbHFLQUpTS0o0L2NIOURYdTlack9WTjdsSEdIYkE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSRENDQWl5Z0F3SUJBZ0lRQ2RnNy9Lb3hodVZmYzd0OTY0WGx0VEFOQmdrcWhraUc5dzBCQVFzRkFEQVQKTVJFd0R3WURWUVFERXdoMllYVnNkQzFqWVRBZUZ3MHhPREV4TWpreE1URXpNemRhRncweE9URXhNamt4TVRFegpNemRhTUJZeEZEQVNCZ05WQkFNVEMzWmhkV3gwTFhaaGRXeDBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUF6SlZ4ak1pbG5xQjBQbHI1dURCdHhtTGVZQVBJYzRoN3BQUDBjUnJsQ0dKb1IwMGIKaHl1WlgyOWxTMHg3MU90Y3BtT2dwemZqTXl5TC94TVkzc2xTOHlva2EzcnYvWkFoWWFIdWtpWWs0MEZoRUYvUQpWay9SU1N4L0l2QXhIYlB0UXFsejRzbzVzVnFlZnlrSmNLcERtS2pEaVloSG9QZURhMjV0bGgwZGMwcWVyMUdGCkNrTWhLVzkrQ2Z3azltcVI1bkw3clhsZjBmWXRTYVVUWmFHTFVyd2o2b0MxeDhWcjg3MVh2OHpCU2g2THdJbFIKV3FPTmtzMjBKU01IaThGZ3hsd3E4bWtzSDBhVUxOUlQ4ZzBqN2IrUm9GQ3luYjduckZWRStDK3ppL05NUVFNdgpmK2VDTlpSOE5yYUxKQ05HcjBQK2hJaTQ3T3ZJVDJod1dCSTIvd0lEQVFBQm80R1FNSUdOTUE0R0ExVWREd0VCCi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVEFRSC8KQkFJd0FEQk9CZ05WSFJFRVJ6QkZnZ3QyWVhWc2RDMTJZWFZzZElJVGRtRjFiSFF0ZG1GMWJIUXVaR1ZtWVhWcwpkSUliWVd0MFlXbGxkaTEyWVhWc2RDNHlNREl4TG5ObGNuWnBZMlZ6aHdSL0FBQUJNQTBHQ1NxR1NJYjNEUUVCCkN3VUFBNElCQVFDdzJlem5oNytVK1dRczBsb25qSE1XcHpYZFhFSG9DQVhyY2VKVWZnNmQ3Qm53U0JEOGtLa2EKNEFHZEh3U2ZFQnpGdnZCL2ZKWnY2eTVGdFR5MmptNHVqWFZRb2lDa29BN1RxM1VwYW9wakk0R3JzUlZ2Vk10RgpBMU1OQXVPWFBjOGltZHZqUDN5cm11ejFUMFlOVVJWUGpZTytEcGtERnJoM2lIRDNTOFB4MS9pM1puYkVoM1hxCmQ4VmpKbUVzMGVMOFQ5RTBhVU9JVUpDLzF2V1AwaU9SeXJzSnY2eXl4bzE2M1lDN0dld2JpUzRzYUJjVXQvYUQKK1diVTI1Vm9vcTl2ZU11VkowNTlmN2hlTkZsVEZoVytiZGY0SmhsSkJYNWF3UmlSSy96cGZXcEo3Wkpmc29RRgppWFpZZXpnYjN6T3BFL1dkS0NGQ2F2L3JmcnJxcWNrdwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBekpWeGpNaWxucUIwUGxyNXVEQnR4bUxlWUFQSWM0aDdwUFAwY1JybENHSm9SMDBiCmh5dVpYMjlsUzB4NzFPdGNwbU9ncHpmak15eUwveE1ZM3NsUzh5b2thM3J2L1pBaFlhSHVraVlrNDBGaEVGL1EKVmsvUlNTeC9JdkF4SGJQdFFxbHo0c281c1ZxZWZ5a0pjS3BEbUtqRGlZaEhvUGVEYTI1dGxoMGRjMHFlcjFHRgpDa01oS1c5K0Nmd2s5bXFSNW5MN3JYbGYwZll0U2FVVFphR0xVcndqNm9DMXg4VnI4NzFYdjh6QlNoNkx3SWxSCldxT05rczIwSlNNSGk4Rmd4bHdxOG1rc0gwYVVMTlJUOGcwajdiK1JvRkN5bmI3bnJGVkUrQyt6aS9OTVFRTXYKZitlQ05aUjhOcmFMSkNOR3IwUCtoSWk0N092SVQyaHdXQkkyL3dJREFRQUJBb0lCQVFDNVE0djBoYThWbXhBcApkNUUwYndhNTVNYWtCRWo5OXRhaFpob3lZcnlOZnpBWGdZZ3dQQmRFQ1VpZGk4R0g2eXVYc2hqRjFTSjJNUjBGCi9IRkZMdU5qT1FLS0ltWTZKTTlWN3FKd3p3SVFtaUFnQitST2hURnRKbEpyZlQrOU9qYmRhejU2WGM4cEFIc1AKaEVYOE5QUEp4dXBzSFhGZ0gwUnZnU3pVQjhHbnFJakgrSDZQTVNJZ09HdjN4SlVYcmFaMnVIQml1dnRiQkxqRwoxWXhmSmppM0VHejEvNStHbHU3emliRng4QzJYMm1HOURlL0pCMFpYb3ZLaFdpYVZzSEFOdGM3TUw2QlVTQ0sxCkpjYjJQZHNTK0pROWJiSHdkc0FLTW9XeVg2MW9lc2ZBRS83c3pYQ2FjUnhSNUQrQ1NNQ2xHKzJneWdXbjl6V2MKVjU1eW1vc2hBb0dCQU9FaVo3TDd3ejc2NnFDM2RoYkQ3NHBiZ2l0VG82Vk5mMytxZGNWMmkrRUI5N1VoUHNFTQp0UHM1dkVWc3hxUkNHcjFDTGxPMUlJVktIZWgwd3NlNkpQSnpyaCtudVdrOUhIdlg5M3QyUHk4Z3M5d1ZzcVd5CngyNVc5MzQvZlFuZlNKeVRDOW8zdDl2UGhFK3Rvb2MwZXFiMGlhVlpNRlVyNFZHNFRxUkpyL2RWQW9HQkFPaWgKeEtUbllyeE5rTVRqditOQUhlWkdiZHZQcnZ2bTdza0taR0cwUlhGUng4ZXJUVWtQUEpaTHBNOHdvUndNTlM1ZwpuRlFsWjF3QmZZOGJ1bDQ0cURtcjEySUZFcVNFT3hQWEFqd2t3UFZNT2tnU2lZNGtaeCtibEdkRWdLQnM4a0ZwCnd2UXNEMjR2WlFTZEZ5OGhNYnJwOTZQNjh1aEt2aHRWdkpobnB3MERBb0dCQUkrVFJIVFZzRitDMzR6ZFUxY1QKWDdscHdHcm5MUzduYkk4N1kxNHB5dTBWTnlieGE3YnI1cU5zMzQrYTNsZTB2SjdFRFExZkxyMHlWajUvOEJRMQp0d2hVRTlDbVEwMUZKdHdvRC9GUnFOdmlUREhvT0lVSnJidkZoSktqNUpjZUtZMkpEWDcrRjZmOEFKSmIxcEhKCk93c3NXbmZ6bUNwSkVLbndFMThjaXpiOUFvR0FjVUlJL2d3Vkd2NWNoQzhweGhiNk41bUVkT2NaRjFVb1hrS3IKK3BHTTJZM3FTUURTZ01abFJmc1FBenQyeExRQTFGSis2Y3pJRkpnNUxBcGc0dXlNb245U1BrdWY5dTdWNEdQbQpsNmVCTml2bG1COUdUeWpUK0NTRHpQOGg3SGorUFBDajFNTDZ4RGRZNURVakMzUUt4U2lSdzRreTUvc3pzUlU5CjI2bGpRRWNDZ1lFQTNwaHQxMDY5Qmg1UTJFMEp0WFJXdjl2MU1pT01GNklzdUpqN2JHQWl2eWNrQWwzeGc0ZEkKWnJsYjJzOWZqRzlzSU4zUit4Qlh4TVlVMkpLaUhreTBHcnA3ZjJraHRtTklwVlRmMzRXNm0zMVR5bFNnMndBTwo5QXE0OTEyTDZna3dvVGpCcVJBK3B4YTJQN1BmSGdoNkhwL21lVGd1R1pCK3dRWit2MWREVkhJPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

kind: Secret
metadata:
  creationTimestamp: 2018-11-29T11:13:38Z
  labels:
    app: vault
    chart: vault-0.5.21
    heritage: Tiller
    release: vault
  name: vault-vault-tls
  namespace: default
  resourceVersion: "2917414"
  selfLink: /api/v1/namespaces/default/secrets/vault-vault-tls
  uid: d252f09d-f3c7-11e8-befa-42010a9c01e1
type: Opaque

To file templates/secrets.yaml added mydomain.com :
{{- $cert := genSignedCert $cn (list "127.0.0.1") (list $cn $externalDNS "mydomain.com") 365 $ca -}}

**Comment by bonifaido** [comment]
Hi, what was the command you executed to check the seal status? The certificate is signed by a generated CA so it won't be whitelisted, you have to use the ca.crt in you client.

**Comment by bonifaido** [comment]
I guess it is coming from the LoadBalancer's Ingress.

**Comment by aaktaev** [comment]
I'm using traefik ingress class
kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/auth-type: "basic"
    traefik.ingress.kubernetes.io/auth-secret: "vault-vault-tls"
    traefik.ingress.kubernetes.io/pass-tls-cert: "true"

**Comment by bonifaido** [comment]
You will have to configure the traefik Helm chart (if you are using that) to use the ca.crt (`rootCAs[0]=/vault/cert/ca.crt`, you will need to mount the vault-vault-tls Secret into the traefik pod) in the from the Vault TLS secret or enable `ssl.insecureSkipVerify=true`.

Please see: https://docs.traefik.io/configuration/backends/kubernetes/#tls-communication-between-traefik-and-backend-pods for the docs.

I will come up with examples in this repo once I have the time

**Comment by aaktaev** [comment]
Hi,
We decided not to change certs fro traefik ingress and use vault without tls(I know it is not secure)

**Comment by matyix** [comment]
OK, I close this for now - feel free to reopen if you have issues or need help.

**Comment by aaktaev** [comment]
Thank you for you help!
