### ISSUE TITLE
Vault-unseal secret doesn't works

### ISSUE THREAD

**Issue by aaktaev** [banzaicloud/banzai-charts#534]
$ kubectl get secret bank-vaults -o yaml
apiVersion: v1
data:
  vault-root: M2IzMzlkZjEtZTFkMS1iYWUxLThkNTMtZTAzNTE4YzE2YTNi
  vault-unseal-0: ZTc4OTRhZjhhNzJiMDg2MzMzYWFjMzM5MjU0NTBjNjQ1NzY5NWY3NDFlZWQ1YjFlZmE0NzA0ZDI5NDk0ZmJlZWYy
  vault-unseal-1: ZDZhMmRlMjU5MTlkNjU1ZDI4M2FlYzkxNTk2MjE5NTdjNTU4MDVlYmZmNDMyNzY4MWYxOWE1N2ZhNTI5M2RkYzFm
  vault-unseal-2: MTA1ZGI0NWVmZGNiYTkzNGQ4MzE0ZjIyNDkzZjBmNGU2MmQ4ZDg5YjAxNTVlYzZhZmUzNGRkZjQ0Nzk1ZjRjZmUx
  vault-unseal-3: OWExY2M3MGVmMmZjODczMjQ3OGMyMDQ1MGFhY2ZkYmY1MGYyZDdlMTBmZjZiYzhkYmZhODBiY2Y3MTVjYzFiZTQz
  vault-unseal-4: YjI3ODJkZjU3YTI4MGE3YjFjOTA5ZDQzMjNlMDk3NDdiODgyZDc3N2U3NThmMjBmNWI5NjA0YzlhYWVjOWRjM2Mx
kind: Secret
metadata:
  creationTimestamp: 2018-11-30T14:12:09Z
  name: bank-vaults
  namespace: default
  resourceVersion: "3294990"
  selfLink: /api/v1/namespaces/default/secrets/bank-vaults
  uid: ec9897f1-f4a9-11e8-befa-42010a9c01e1
type: Opaque

$ ./vault operator unseal
Unseal Key (will be hidden):
Error unsealing: Error making API request.

URL: PUT http://mydomain.com:8200/v1/sys/unseal
Code: 400. Errors:

* invalid key: key is longer than maximum 33 bytes

**Comment by bonifaido** [comment]
Hi @aaktaev, these keys are (as all Kubernetes secrets) base64 encoded, so you have to decode them first, on the other hand, bank-vaults handles unsealing for you, so you never have to call `vault operator unseal` manually.

**Comment by aaktaev** [comment]
Thanks.After decoding it works.
