### ISSUE TITLE
"vaults.vault.banzaicloud.com" already exists

### ISSUE THREAD

**Issue by rahmnathan** [banzaicloud/banzai-charts#606]
When attempting to install this for the first time in a Kube cluster I'm getting the following error:

Error: release coiled-wallaby failed: customresourcedefinitions.apiextensions.k8s.io "vaults.vault.banzaicloud.com" already exists

I've found that commenting out the annotations in the 'CustomResourceDefinition' file allows the chart to be installed, though it does not appear to be functional.

**Comment by kozmagabor** [comment]
Hi,

Sorry, I cannot reproduce.
I think the `helm` left some garbage there from a previous trying.

How to try to install it?
Could you share  more information?

`kubectl get crd vaults.vault.banzaicloud.com -o yaml` <- Is it exists?

Regards,
gabo

**Comment by rahmnathan** [comment]
Thanks for the quick response @kozmagabor. The command I'm using to install comes from the ReadMe.md

`helm install banzaicloud-stable/vault-operator --set etcd-operator.enabled=true`

The following is the set of commands I have just run along with their outputs:

`kubectl get crd vaults.vault.banzaicloud.com -o yaml`

Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "vaults.vault.banzaicloud.com" not found

`helm install banzaicloud-stable/vault-operator --set etcd-operator.enabled=true`

Error: release unrealistic-wallaby failed: customresourcedefinitions.apiextensions.k8s.io "vaults.vault.banzaicloud.com" already exists

**Comment by rahmnathan** [comment]
For more information: My Kubernetes instance is deployed via Rancher. It does not have any dynamic persistent volume provisioning (if that matters). The output from `kubectl version` is:


Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
