### ISSUE TITLE
Deadlock on vault-operator update

### ISSUE THREAD

**Issue by szymonpk** [banzaicloud/banzai-charts#608]
I am not sure if this issue should be raised here on in operator repo.

Steps to reproduce:
1. Deploy vault-operator, with default values (replicaCount: 1)
2. Change values and upgrade running operator with `helm upgrade`

It results in deadlock, old pod is still running, new pod tries to start and it cannot aquire a lock which is held with old pod:

```
{"level":"info","ts":1547553963.9364433,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1547553964.150086,"logger":"leader","msg":"Found existing lock","LockOwner":"bank-vaults-operator-vault-operator-777d97c68d-8j5xg"}
{"level":"info","ts":1547553964.2477176,"logger":"leader","msg":"Not the leader. Waiting."}
```

I cannot destroy whole helm deployment on upgrade because it destroys CRD as well. What is best approach to this issue? I was thinking about `deploymentStrategy: Recreate`, it will destroy old pods first.

**Comment by bonifaido** [comment]
Hi @szymonpk, yes, we thought the leader election mechanism works with signaling, but we were, wrong, updated the deployment accordingly, and it works fine. Thank you for reporting this!

**Comment by baluchicken** [comment]
Thanks @szymonpk, we added `deploymentStrategy: Recreate`  to our chart but I think this is just a temporary solution. The error is inside the [operator-sdk](https://github.com/operator-framework/operator-sdk) we are using. We are going to open an issue about this, and will update bank-vaults operator when fixed in the framework.

**Comment by szymonpk** [comment]
Thank you very much, I see it is [already in the works](https://github.com/operator-framework/operator-sdk/issues/920). I wasn't sure if it was intended. I agree that recreate may be less than ideal.
