### ISSUE TITLE
Can't create vault instances in non-operator namespace.

### ISSUE THREAD

**Issue by rahmnathan** [banzaicloud/banzai-charts#616]
I've installed the vault-operator via Helm and was able to create a Vault instance in the same namespace as the operator using the cr-etd-ha.yaml file (and I'd like to thank the community here for getting me this far). The problem I have now is I can't get Vault instances to deploy outside of the operator namespace. When I installed the operator chart, I left 'watchNamespaces', which means it should be watching all namespaces. When I attempt to create a Vault instance in another namespace, I see the following statement in the operator logs:

`{"level":"info","ts":1547744927.7923923,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"my-namespace","Request.Name":"vault"}`

But I don't see any pods show up in the desired namespace. I've been digging around and haven't been able to find any error messages. Where should I be looking?

**Comment by bonifaido** [comment]
Could you please check if there are any statefulsets in the defined namespace, and if yes in what state they are?

**Comment by rahmnathan** [comment]
@bonifaido Ah yes! There is an entry of:

`vault   2         0         2m`

I'm not very familiar with statefulsets, but that lead me to:

`create Pod vault-0 in StatefulSet vault failed error: pods "vault-0" is forbidden: error looking up service account fabric-dev/vault-operator: serviceaccount "vault-operator" not found`

So presumably that serviceaccount is only created in the namespace that I install the operator in. How can I go about fixing that?

**Comment by bonifaido** [comment]
I think the serviceAccount that you have defined to be used by Vault, doesn't exist in the given namespace.

Could you please post your CRD here?

**Comment by rahmnathan** [comment]
@bonifaido The etcd cluster is not starting in this namespace (though it should). When I deploy this crd to the namespace that contains both the vault-operator and etcd-operator, etcd starts and then Vault starts successfully. When I try to deploy this crd to another namespace, only Vault is starting now which of course causes it to fail.

Is there some configuration to tell the etcd-operator to watch all namespaces and/or is there something I need to manually do to my namespace to get etcd to deploy to it (like a missing serviceaccount or something)?

**Comment by bonifaido** [comment]
Currently the etcd-operator helm chart (which we pull from the stable community chart repo) doesn't support cluster-wide managing of etcd resources by default, see: https://github.com/coreos/etcd-operator/blob/master/doc/user/clusterwide.md
https://github.com/helm/charts/blob/master/stable/etcd-operator/templates/operator-deployment.yaml

But, it can be enabled via custom command line arguments, this needs to be worked out (I haven't tried yet!):

```helm upgrade --install vault-operator . --set=etcd-operator.enabled=true --set=etcd-operator.etcdOperator.commandArgs.cluster-wide=true```

Maybe I'm missing something, but this flag was added in https://github.com/coreos/etcd-operator/blob/aeb3e3e0835ec5135cfe50340f59853b5b6fc407/CHANGELOG.md#added-3 but I couldn't make it work.

Could you please try as well, and if it is not working open up an issue upstream in etcd?

**Comment by rahmnathan** [comment]
Ah! Along with @bonifaido's Helm command, I needed to enable the etcd 'cluster-wide' annotation in my crd. It was there all along, but was commented out by default. After those two changes, the etcd crd is now available cluster-wide. Thanks @bonifaido

**Comment by bonifaido** [comment]
Hi @rahmnathan! This is great, I didn't know that an annotation has to be added to the etcd pod as well! I glad you could make this work! I will update the documentation with the clusterwide etcd settings.

**Comment by rahmnathan** [comment]
@bonifaido So I'm unfortunately still having issues here. etcd appears to be good now, but I'm having some odd errors with Vault. Again, this is only happening outside of the vault-operator namespace. When trying to deploy into another namespace, all applicable resources appear to get created properly, but I'm getting an error event on the vault pods of:

`Readiness probe failed: HTTP probe failed with statuscode: 503`

In the vault pod's log I see (this may be unrelated, though, as I also see it in the vault-operator namespace where everything appears functional):

`[ERR] Error flushing to statsd! Err: write udp [::1]:48575->[::1]:9125: write: connection refused`

and in the vault-configurer logs:

`level=error msg="error checking if vault is sealed: error checking status: Get https://vault.did-dev:8200/v1/sys/seal-status: dial tcp 10.43.204.182:8200: i/o timeout, waiting 30s before trying again..."`

If I port-forward to the pod, I am able to see the ui, though the Vault is sealed and thus is inaccessible. 


An additional question, the vault service appears to default to NodePort. Is there a way to configure this? NodePort is not very useful to me in a production environment. I'd rather have it as a ClusterIP and put an Ingress in front of it.

Thanks

**Comment by bonifaido** [comment]
> Readiness probe failed: HTTP probe failed with statuscode: 503

This operator uses Vault in a StatefulSet and in HA mode only one of the instances will become `READY`, this is how we handle that only the active Vault instance gets traffic through the Kubernetes Service.

> [ERR] Error flushing to statsd! Err: write udp [::1]:48575->[::1]:9125: write: connection refused
Timing issue, Vault flushed the first batch of stats, but the statsd container wasn't ready yet, this gets fixed when it becomes ready, in a few seconds.

Did you try to access the active Vault instance (`3/3`)?

NodePort can be changed via `serviceType`, see https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/apis/vault/v1alpha1/vault_types.go#L51
It was left NodePort at the beginning and remained the default for compatibility reasons, but I guess its time to change it to ClusterIP.

**Comment by rahmnathan** [comment]
Additional info. I setup an ingress in front of this deployment and get a 503 response on every request. When I port-forward to either pod I get to the UI, but It says that the Vault is sealed to I'm unable to do anything with it. Seems like the service isn't forwarding requests to the pods for some reason (based on both the ingress and vault-configurer failures).

**Comment by bonifaido** [comment]
Can you make sure that Vault has managed to connect to your etcd backend? I suspect that it has some issues.

**Comment by rahmnathan** [comment]
@bonifaido Just got this resolved. The secret was hidden in the bank-vaults logs of my Vault pods. The service account I had assigned to the deployment didn't have permissions to manage secrets in the namespace I was deploying to. After creating an appropriate role and role-binding, the deployment succeeds and I can access Vault through the Ingress.

Thanks for your help @bonifaido. I'm still learning about Vault and Kubernetes, so this feedback has been very valuable!

**Comment by bonifaido** [comment]
You're welcome @rahmnathan! Could you please describe how bank-vaults, and charts or just the documentation could have been better, so your workflow would have been easier at first?

**Comment by rahmnathan** [comment]
@bonifaido I think a step-by-step installation/usage tutorial for a vanilla Vault + etcd instance would be great. I also think it's important that it's explained via deploying the operators in their own namespace, as my view is the operator is a cluster-wide tool and most teams won't actually deploy a Vault instance along side the operator in the same namespace. In addition to that, the details of the issues I found were usually hidden in a log somewhere, but there are quite a few components to sift through to find them. An inventory/trouble-shooting guide would be a good addition to the step-by-step guide. Something like "If you have x issue, check y". Examples that I ran into were: 'describe' the stateful set to find a missing service account error, check the bank-vault logs in the Vault pods to find that the service account didn't have the appropriate permissions, etc.

I already have that issue open about loading some boilerplate configuration during the installation. I still think this would be very useful from an automation standpoint.

The other thing that would be nice is a durable alternative to the etcd back-end. I know I can deploy any back-end that I want and then point to it in my crd, but the way etcd is integrated here is very nice/easy to use and it'd be nice if there was an alternative that provided some persistence as I can't imagine using this in production without persistence as you'd run the risk of losing all of your configuration.

Overall, I'm excited about this vault-operator and hope that myself (and team) can move forward with this as it really streamlines our Vault deployments. It's likely I'll end up opening other issues as I continue to dive into this, but I have to say I'm very happy with the support I gathered here (mostly from yourself). I probably would've given up and moved onto another solution had the responses not been so quick/helpful.

One last thing. As far as being production-ready, is there anything that I may be missing/should be aware of? We're at the early stages of integrating this into our system, but I want to make sure I'm aware of any potential issues.

Thanks!

**Comment by bonifaido** [comment]
Thank you @rahmnathan, your feedback is highly valuable. We just started to create an extensive documentation with fully working examples as well, since most of our issues are coming because of black-holes in our docs and guides (mostly the blog entries are our guides).

Yes, the etcd backend needs to become durable, this should be configurable, I have created an issue on the upstream bank-vaults project for this. Since the etcd backend currenly in the operator is mostly for demonstrational purposes and etcd should be configured via a separate CRD we haven't spent to much time on this yet, see: https://github.com/banzaicloud/bank-vaults/issues/301

I think if you are using the etcd backend currently for production in Vault I suggest to create an etcd cluster directly with the etcd operator.

**Comment by rahmnathan** [comment]
@bonifaido Thanks for taking actions on my requests! Very much appreciated. As far as documentation, it seems like most of it is there, it just needs to be organized/centralized. Like you mentioned, most of what I was looking for was either in: the ReadMe, the comments of the deployment files, or a blog post. It was just sort of hard to navigate and find what I was looking for.

Thanks for the info and for creating that ticket.
