### ISSUE TITLE
HPA-operator uses only custom.metrics.k8s.io/v1beta1.

### ISSUE THREAD

**Issue by fog1985** [banzaicloud/banzai-charts#657]
HI.
Is it possible to point `hpa-operator` to `metrics.k8s.io/v1beta1` instead of `custom.metrics.k8s.io/v1beta1`?

Cuz here what I have:
```
tklym@Tarass-MacBook-Pro-2 hammertime (DEVOPS-216) $ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/hammertime-production/pods
Error from server (NotFound): the server could not find the metric  for pods

tklym@Tarass-MacBook-Pro-2 hammertime (DEVOPS-216) $ kubectl get --raw /apis/metrics.k8s.io/v1beta1/namespaces/hammertime-production/pods
{"kind":"PodMetricsList","apiVersion":"metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/metrics.k8s.io/v1beta1/namespaces/hammertime-production/pods"},"items":[{"metadata":{"name":"hammertime-69bbdbdb85-b9v9t","namespace":"hammertime-production","selfLink":"/apis/metrics.k8s.io/v1beta1/namespaces/hammertime-production/pods/hammertime-69bbdbdb85-b9v9t","creationTimestamp":"2019-02-08T09:12:10Z"},"timestamp":"2019-02-08T09:11:22Z","window":"30s","containers":[{"name":"hammertime-rails","usage":{"cpu":"162556n","memory":"343180Ki"}}]}
...
```
And of course HPA-operator:
```
tklym@Tarass-MacBook-Pro-2 Repositories $ kubectl logs  hpa-operator-hpa-operator-7676466bf9-q7m65 | tail -3
ERROR: logging before flag.Parse: E0208 09:10:26.887858       1 memcache.go:153] couldn't get resource list for custom.metrics.k8s.io/v1beta1: <nil>
ERROR: logging before flag.Parse: E0208 09:11:26.886155       1 memcache.go:153] couldn't get resource list for custom.metrics.k8s.io/v1beta1: <nil>
ERROR: logging before flag.Parse: E0208 09:12:26.886879       1 memcache.go:153] couldn't get resource list for custom.metrics.k8s.io/v1beta1: <nil>
```

**Comment by sancyx** [comment]
It makes no sense to point to metrics.k8s.io/v1beta1. The attached log, looks it's a bit strange to me because hpa-operator is not fetching metrics directly, it only creates/updates HorizontalPodAutoscaler objects which are responsible for scaling. If you have metrics server running (you have to set metricsServer.enabled=true in hpa-operator chart) you have cpu & memory metrics available from metrics.k8s.io/v1beta1, don't need to change anything, so scaling should work with these basic metrics provided by metrics server. To have custom metrics you need a custom metrics server like https://github.com/banzaicloud/banzai-charts/tree/master/prometheus-adapter which exposes metrics from Prometheus on custom.metrics.k8s.io/v1beta1, so that you are able to setup HPA to use this. You can find a more detailed explanation here: https://banzaicloud.com/blog/k8s-horizontal-pod-autoscaler/

**Comment by sancyx** [comment]
So to summarize hpa-operator is not responsible for the actual scaling it's a helper operator with create updates HPA objects, then in a HPA object you can use cpu & mem by default they are available or you custom metrics. You can try creating a small cluster & setup horizontal autoscale for a deployment here using Pipeline (https://beta.banzaicloud.io/ui) or provide some more info like what you exactly want to do, you env etc.

**Comment by fog1985** [comment]
Hi @sancyx ,
Thanks for the reply.
So. I have tried as you pointed out to use `metricsServer.enabled=true`
It returned:
```
1 error(s) occurred:

* helm_release.hpa-operator: 1 error(s) occurred:

* helm_release.hpa-operator: rpc error: code = Unknown desc = no APIService with the name "v1beta1.metrics.k8s.io" found
```
Metrics-server is installed and works:
```
tklym@Tarass-MacBook-Pro-2 Repositories $ kubectl top pods -n hammertime-production
NAME                          CPU(cores)   MEMORY(bytes)
hammertime-64dc4f7594-5gkt4   1m           308Mi
hammertime-64dc4f7594-5sfnv   1m           352Mi
hammertime-64dc4f7594-fmr9w   1m           470Mi
hammertime-64dc4f7594-hqdh9   1m           337Mi
hammertime-64dc4f7594-htfn6   1m           353Mi
hammertime-64dc4f7594-lpdv7   1m           399Mi
hammertime-64dc4f7594-n44sj   1m           379Mi
hammertime-64dc4f7594-wcz6b   1m           450Mi
hammertime-64dc4f7594-xk74j   1m           333Mi
hammertime-64dc4f7594-z7nbd   1m           341Mi
```
And you have seem `raw` output as well.
But `HPA object created by HPA-operator` doesn't see it and I can't figure out where it actually looks for the metrics:
```
tklym@Tarass-MacBook-Pro-2 Repositories $ kubectl get hpa -n hammertime-production
NAME         REFERENCE               TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
hammertime   Deployment/hammertime   <unknown>/70%   10        25        10         110m
```
As you see, it knows limits and threshold for scaling but it has no idea about present situation: `<unknown>`

**Comment by fog1985** [comment]
I don't need custom metrics etc. 
All I need it just scale based on either `memory` or `cpu`.

**Comment by sancyx** [comment]
let's describe the hpa object there should be some additional details:  ```kubectl describe hpa```

**Comment by fog1985** [comment]
```
$ kubectl describe hpa -n hammertime-production
Name:                                                     hammertime
Namespace:                                                hammertime-production
Labels:                                                   <none>
Annotations:                                              <none>
CreationTimestamp:                                        Fri, 08 Feb 2019 12:50:27 +0200
Reference:                                                Deployment/hammertime
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  <unknown> / 70%
Min replicas:                                             10
Max replicas:                                             25
Deployment pods:                                          10 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: no metrics returned matched known pods
Events:
  Type     Reason                   Age                   From                       Message
  ----     ------                   ----                  ----                       -------
  Warning  FailedGetResourceMetric  48s (x579 over 145m)  horizontal-pod-autoscaler  no metrics returned matched known pods
```

**Comment by sancyx** [comment]
Could you please also attach the output of ```kubectl gey hpa -o ``` just to see the full definition of hpa. What Kubernetes version are you using?

**Comment by sancyx** [comment]
I'm asking about k8s version because there are some similar issues like yours (https://github.com/kubernetes/kubernetes/issues/63786) may be you can check if you deployment spec has resource requests defined for containers: containers[0].resources.requests.memory.

**Comment by fog1985** [comment]
Ok. Now I see that the issue is not in HPA but in something particularly related with the app.
But what exactly wrong - have no idea.

I have manually created autoscaling using command as follow:
`kubectl autoscale -n hammertime-production deployment hammertime --cpu-percent=50 --min=1 --max=10`

And created just simple app (php-blabla) from k8s docs and autoscaled exactly the same in the same namespace.
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

Here what I got:
```Every 2.0s: kubectl get hpa -n hammertime-production           Tarass-MacBook-Pro-2.local: Fri Feb  8 18:10:46 2019

NAME         REFERENCE               TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
hammertime   Deployment/hammertime   <unknown>/70%   10        25        10         11m
php-apache   Deployment/php-apache   0%/50%          1         10        1          3m57s```

Any thoughts on why `hammertime`’s cpu metrics can’t be recognized by `hpa`?

**Comment by fog1985** [comment]
Both of these apps are having metrics gathered by metrics-server:
```
tklym@Tarass-MacBook-Pro-2 hammertime (DEVOPS-216) $ kubectl get --raw /apis/metrics.k8s.io/v1beta1/namespaces/hammertime-production/pods/php-apache-b5f58cc5f-2fv9n
{"kind":"PodMetrics","apiVersion":"metrics.k8s.io/v1beta1","metadata":{"name":"php-apache-b5f58cc5f-2fv9n","namespace":"hammertime-production","selfLink":"/apis/metrics.k8s.io/v1beta1/namespaces/hammertime-production/pods/php-apache-b5f58cc5f-2fv9n","creationTimestamp":"2019-02-08T16:15:57Z"},"timestamp":"2019-02-08T16:15:44Z","window":"30s","containers":[{"name":"php-apache","usage":{"cpu":"16771n","memory":"9364Ki"}}]}

tklym@Tarass-MacBook-Pro-2 hammertime (DEVOPS-216) $ kubectl get --raw /apis/metrics.k8s.io/v1beta1/namespaces/hammertime-production/pods/hammertime-64dc4f7594-z7nbd
{"kind":"PodMetrics","apiVersion":"metrics.k8s.io/v1beta1","metadata":{"name":"hammertime-64dc4f7594-z7nbd","namespace":"hammertime-production","selfLink":"/apis/metrics.k8s.io/v1beta1/namespaces/hammertime-production/pods/hammertime-64dc4f7594-z7nbd","creationTimestamp":"2019-02-08T16:16:03Z"},"timestamp":"2019-02-08T16:15:45Z","window":"30s","containers":[{"name":"hammertime-rails","usage":{"cpu":"161803n","memory":"351084Ki"}}]}
```

**Comment by sancyx** [comment]
Try to compare the definition of these two pods, there's should be some difference which is the cause of this problem. Have you check you have resource requests defined in your pod spec?

**Comment by fog1985** [comment]
So. The issue was in the `Deployment`.
It defined resources and requirements for the pods as follow:
```
        resources:
          limits:
            cpu: 700m
            memory: 768Mi
          requests:
            cpu: "0"
            memory: "0"
```
And `request` in `0` actually blocked HPA from measuring CPU etc.
Once I deleted this section everything started to work. :)
