### ISSUE TITLE
[Mysql Operator] Your port of the oracle operator is not keeping up with the upstream

### ISSUE THREAD

**Issue by ballad89** [banzaicloud/banzai-charts#701]
I read your [blogpost on mysql on kubernetes](https://banzaicloud.com/blog/mysql-on-kubernetes/) and would like to use it, but I noticed your version of the operator is not up to date with the upstream.

Do you no longer track the upstream ? Or do you regularly merge the changes which are relevant ?

**Comment by kozmagabor** [comment]
Hi @ballad89 

We are tracking it, but they haven't released a new version from the operator recently.

Regards,
Gabo
