### ISSUE TITLE
Azure Storage Provider error deploying Thanos Store

### ISSUE THREAD

**Issue by bamb00** [banzaicloud/banzai-charts#709]
Hi, I'm running into an issue with deploying thanos-prometheus using provider azure for objstore.   Can you tell me what I am doing wrong? Thanks.

        MountVolume.SetUp failed for volume "thanos-config-volume" : secret "prometheus-thanos" not found
        MountVolume.SetUp failed for volume "azure" : secret "prometheus-thanos" not found

Values.yaml

     objstore:
       provider: azure
       configFile: "bucket.yaml"
       config: |-
          type: AZURE
         config:
           storage_account: "thanossa"
           storage_account_key: "azure---storageaccount---access--keys"
           container: "thanos"

**Comment by tarokkk** [comment]
We are moved to `prometheus-operator` and `thanos` chart separately. We suggest you use that set-up.
