### ISSUE TITLE
Check service accounts and roles

### ISSUE THREAD

**Issue by pbalogh-sa** [banzaicloud/banzai-charts#717]
- inspect all used charts, in order to define proper psp and network policies
- specify service accounts for starting containers

**Comment by InTheCloudDan** [comment]
I think this is related to the issue I was about to open on bank-vaults operator. Not sure if it should be opened there instead of here. Running a clean install I'm getting:
```
Error: container has runAsNonRoot and image has non-numeric user (vault-operator), cannot verify user is non-root
```

I don't see options to configure it.

**Comment by pbalogh-sa** [comment]
hello @InTheCloudDan, thanks for reporting this.The vault-operator application is running in name of vault-operator user which doesn't exist on node, so securityContext runAsNonRoot cannot check whether vault-operator user is root or not. I have opened the issue in bank-vaults repo: https://github.com/banzaicloud/bank-vaults/issues/367

**Comment by pbalogh-sa** [comment]
@InTheCloudDan you can use `runAsUser: 1000` instead of runAsNonRoot as a workaround until fix.

**Comment by pbalogh-sa** [comment]
@InTheCloudDan , it's fixed: https://github.com/banzaicloud/bank-vaults/releases/tag/0.4.14
imageTag: master or 0.4.24

**Comment by InTheCloudDan** [comment]
great thank you!!
