### ISSUE TITLE
Vault secret webhook and non default namespaces

### ISSUE THREAD

**Issue by Johnch9** [banzaicloud/banzai-charts#811]
When trying to deploy the sample application into a 'test' namespace we are getting a vault authentication error.  Everything works if we deploy into default.  Is there something we are missing when using namespaces?

Error:

`2019/05/09 19:10:21 Failed to request new Vault token Error making API request.

URL: PUT https://52.178.35.131:8200/v1/auth/kubernetes/login
Code: 500. Errors:

* service account name not authorized
2019/05/09 19:10:26 Failed to request new Vault token Error making API request.

URL: PUT https://52.178.35.131:8200/v1/auth/kubernetes/login
Code: 500. Errors:

* service account name not authorized`

Test file:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets-test
  template:
    metadata:
      labels:
        app: hello-secrets-test
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://52.178.35.131:8200"
        vault.security.banzaicloud.io/vault-role: "test-app-role"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        # vault.security.banzaicloud.io/vault-agent: "true"
    spec:
      initContainers:
      - name: init-ubuntu
        image: ubuntu
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo initContainers ready"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY

**Comment by bonifaido** [comment]
How do you configure `test-app-role` in Vault?

**Comment by Johnch9** [comment]
vault write auth/kubernetes/role/test-app-role bound_service_account_names=vault-auth bound_service_account_namespaces=test policies=test-app-policy

There is a vault-auth service account in test namespace

**Comment by bonifaido** [comment]
The deployment has to run in this service account then: `vault-auth`

**Comment by Johnch9** [comment]
That makes sense, many thanks for the quick response

**Comment by bonifaido** [comment]
You're welcome, I hope it works now! :)

**Comment by bonifaido** [comment]
Feel free to reopen if needed.

**Comment by Johnch9** [comment]
I think I'm still missing a step somewhere

In vault I've run
`vault write auth/kubernetes/role/test-app5-role bound_service_account_names=test-app5-admin bound_service_account_namespaces=test-app5 policies=test-app5-policy ttl=1h`

KubeConfig ServiceAccount JWT token appears to be correct:
  "kubernetes.io/serviceaccount/namespace": "test-app5",
  "kubernetes.io/serviceaccount/secret.name": "test-app5-admin-token-9kk8t",
  "kubernetes.io/serviceaccount/service-account.name": "test-app5-admin"

Not sure if I need this but I added the ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: test-app5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: test-app5-admin
  namespace: test-app5

But I still get an error deploying the bank-vaults test-deployment.yaml
Code: 500. Errors:

* service account name not authorized
2019/05/11 09:31:54 Failed to request new Vault token Error making API request.

Deployment is
kind: Deployment
metadata:
  name: hello-secrets-test-5
  namespace: test-app5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets-test-5
  template:
    metadata:
      labels:
        app: hello-secrets-test-5
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://X.X.X.X:8200"
        vault.security.banzaicloud.io/vault-role: "test-app5-role"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
        # vault.security.banzaicloud.io/vault-agent: "true"
    spec:
      initContainers:
      - name: init-ubuntu
        image: ubuntu
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo initContainers ready"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/test-app2/aws#AWS_SECRET_ACCESS_KEY
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/test-app2/aws#AWS_SECRET_ACCESS_KEY

**Comment by Johnch9** [comment]
Ok got it - I was missing

`      serviceAccountName: test-app5-admin
      automountServiceAccountToken: true`

in the Deployment spec :(
