### ISSUE TITLE
[vault-secrets-webhook] Specify namespaceSelector

### ISSUE THREAD

**Issue by marcoreni** [banzaicloud/banzai-charts#814]
Hello,

We'd like to experiment with the webhook, and we'd like to start by limiting it to a specific namespace.

In https://github.com/banzaicloud/banzai-charts/blob/master/vault-secrets-webhook/templates/apiservice-webhook.yaml#L42 there is a notIn related to the namespace the webhook is installed in (due to the recursion issue).

Would it make sense to expand this configuration and make it possible to declare a namespace (or a list of namespaces) to be monitored?

**Comment by bonifaido** [comment]
Hi @marcoreni, that would absolutely make sense, are you planning to do that? If so, we are happy to discuss/merge it, that would be a great addition.

**Comment by marcoreni** [comment]
I can definitely try :)
