### ISSUE TITLE
hpa-operator unknown field "allowPrivilegeEscalation"

### ISSUE THREAD

**Issue by denmaddog** [banzaicloud/banzai-charts#855]
Hello,

When installing on k8s v 1.14.3:

helm install banzaicloud-stable/hpa-operator
Error: validation failed: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(Deployment.spec.template.spec.securityContext): unknown field "capabilities" in io.k8s.api.core.v1.PodSecurityContext]

Any idea?

Thanks!

**Comment by pbalogh-sa** [comment]
@denmaddog  thanks for reporting this, if you use helm version v2.14 the validation will faile due to PodSecurityContext doesn't have capabilities and allowPrivilegeEscalations fields. We have fixed it in PR: #856

**Comment by denmaddog** [comment]
Hi guys,

I've done local changes following fix, but now there is another error:

helm install -n hpa-operator banzai-charts/hpa-operator/
Error: validation failed: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext
