### ISSUE TITLE
[vault-operator]: Documented resource limits don't match defaults

### ISSUE THREAD

**Issue by dcherman** [banzaicloud/banzai-charts#911]
In the vault-operator helm chart, the documented values for `resource.limits` are nil, however you do have defined values in `values.yaml`.  Also missing documentation for the `requests`

**Comment by bonifaido** [comment]
Nice catch @dcherman! Would you mind sending a PR for that? The values is the truth so I guess the Readme has to be fixed.

**Comment by dcherman** [comment]
Sure
