### ISSUE TITLE
[vault-operator] Make bearerTokenFile path configurable

### ISSUE THREAD

**Issue by jshrack-ssi** [banzaicloud/banzai-charts#929]
**Is your feature request related to a problem? Please describe.**
Currently the service monitor CRD for vault has a statically defined path for the bearerTokenFile based on the assumption you are storing the Vault token for Prometheus in a Kubernetes secret. This is not good if you are using either webhook injection or vault-agent to attain your token and integrating with Prometheus Operator. 

**Describe the solution you'd like to see**
Make the bearerTokenFile path configurable so it is more flexible when using alternative methods of attaining a token for Prometheus from Vault.

**Comment by bonifaido** [comment]
Fixed already, please see bank-vaults repo.
