### ISSUE TITLE
Thanos: please add Thanos Rule component to the chart

### ISSUE THREAD

**Issue by qingkunl** [banzaicloud/banzai-charts#954]
**Is your feature request related to a problem? Please describe.**

I'd like to use this chart to deploy all Thanos components, but it seems like the Rule component ([https://thanos.io/components/rule.md/](url)) is not there yet.

**Describe the solution you'd like to see**

Please add the support for the Rule component. Thanks.

**Comment by tarokkk** [comment]
https://github.com/banzaicloud/banzai-charts/releases/tag/thanos%2F0.3.8
