### ISSUE TITLE
[Cadence]: Unable to install cadence chart locally.

### ISSUE THREAD

**Issue by SachinHg** [banzaicloud/banzai-charts#963]
**Describe the bug**

Hi, I cloned this repository on to my computer and tried to install cadence helm chart using helm install command.

**Steps to reproduce the issue:**
`git clone git@github.com:banzaicloud/banzai-charts.git`
`cd banzai-charts/cadence`
`helm install --name my-release --namespace cadence <location to cadence chart.yaml>` 

I get an error like this 
```
Error: render error in "cadence/templates/server-job.yaml": template: cadence/templates/server-job.yaml:42:51: executing "cadence/templates/server-job.yaml" at <include "cassandra.h...>: error calling include: template: cadence/templates/_helpers.tpl:270:22: executing "cassandra.host" at <include "call-nested...>: error calling include: template: cadence/templates/_helpers.tpl:53:4: executing "call-nested" at <include $template (d...>: error calling include: template: no template "cassandra.fullname" associated with template "gotpl"
```

P.S, I have tried `helm install --set cassandra.enabled=false --set mysql.enabled=true --set mysql.mysqlPassword=cadence banzaicloud-stable/cadence` and it works as expected.

**Additional context**

I am using Helm version v2.10.0
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Comment by tarokkk** [comment]
The Chart repo exists to avoid these kind of problems. The render error indicates that requirements chart is missing. You need to `help dep build` to collect these dependencies. But I suggest you to use the Chart from the banzai-stable repo.

**Comment by SachinHg** [comment]
hey @tarokkk, can you please point me to the url banzai-stable repo ?
Thanks
