### ISSUE TITLE
Build Thanos chart 0.3.8

### ISSUE THREAD

**Issue by qingkunl** [banzaicloud/banzai-charts#966]
The previous PR https://github.com/banzaicloud/banzai-charts/pull/960 has added the autoDownsampling configuration and bumped the chart version to 0.3.8. However, the 0.3.8 chart still hasn't been built into the banzaicloud repo.

> $ helm repo list
> NAME              	URL
> banzaicloud-stable	https://kubernetes-charts.banzaicloud.com
> 

> $ helm repo update banzaicloud-stable
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "banzaicloud-stable" chart repository
> Update Complete.

> $ helm search thanos
> NAME                     	CHART VERSION	APP VERSION	DESCRIPTION
> banzaicloud-stable/thanos	0.3.7        	0.8.1      	Thanos is a set of components that can be composed into a...

**Comment by tarokkk** [comment]
I wanted to include the rule deployment as well before release but I got some difficulties please be patient tomorrow we will release new version

**Comment by qingkunl** [comment]
Got it. Thanks!

**Comment by tarokkk** [comment]
https://github.com/banzaicloud/banzai-charts/releases/tag/thanos%2F0.3.8
