### ISSUE TITLE
[chart/thanos] Releasing thanos bucket web 0.9.0 fails for change in flag name

### ISSUE THREAD

**Issue by jecnua** [banzaicloud/banzai-charts#984]
**Describe the bug**

The new thanos version (0.9.0) changes the flag in the bucket component (thanos bucket web) from --listen to --http-address. Trying to release the new version with the latest thanos chart will result in the pod failing with this error:

```
Error parsing commandline arguments: unknown long flag '--listen'
thanos: error: unknown long flag '--listen'
```

**Steps to reproduce the issue:**
Release thanos 0.9.0 web component with the latest helm chart here.

**Expected behavior**
Pod should be running.

**Additional context**

You can test the flags here:
docker run -it --name test --rm --entrypoint thanos quay.io/thanos/thanos:v0.8.1 bucket web --help
and
docker run -it --name test --rm --entrypoint thanos quay.io/thanos/thanos:v0.9.0 bucket web --help

**Comment by MyMirelHub** [comment]
I had the same problem. The Thanos team have removed the `--listen` flag in this [PR](https://github.com/thanos-io/thanos/pull/1712) and use `--http-address` instead.

**Comment by jecnua** [comment]
Looks like was fixed here https://github.com/banzaicloud/banzai-charts/commit/e5e72de85d43bab1098e269cdf37b8bb020cf615a 9 days ago. I found it by chance however while checking what to change after fork. -.- @MyMirelHub in case you still need this too should be there in the last version.
