### ISSUE TITLE
[chart/Thanos] - compact parameters

### ISSUE THREAD

**Issue by acarsercan** [banzaicloud/banzai-charts#996]
Hi,

Thanos documentation suggests:

 _The goal of downsampling is providing an opportunity to get fast results for range queries of big time intervals like months or years. In other words, if you set --retention.resolution-raw less then --retention.resolution-5m and --retention.resolution-1h - you might run into a problem of not being able to “zoom in” to your historical data._

Yet banzai thanos chart has raw less than resolution 5m & 1h
Is this correct? or I have read it wrong?

Regards

**Comment by tarokkk** [comment]
Those are just example values. You should consider how you want to use Thanos. If you want to zoom in into archiva data you should set the same retention values, if you don't need exact values just want to check tendencies in a 1y resolution you don't need them.
